{
   "active_lock_reason" : null,
   "assignee" : null,
   "assignees" : [],
   "author_association" : "MEMBER",
   "body" : "https://github.com/bitcoin/bitcoin/actions/runs/7667501768/job/20897463395\r\n\r\n```bash\r\n ============\r\nCombined log for D:\\a\\_temp/test_runner_â¿_ð_20240126_113602/feature_index_prune_293:\r\n============\r\n\r\n test  2024-01-26T11:36:28.165000Z TestFramework (INFO): PRNG seed is: 8852427722333217080 \r\n test  2024-01-26T11:36:28.165000Z TestFramework (DEBUG): Setting up network thread \r\n test  2024-01-26T11:36:28.212000Z TestFramework (INFO): Initializing test directory D:\\a\\_temp\\test_runner_â¿_ð_20240126_113602\\feature_index_prune_293 \r\n test  2024-01-26T11:36:28.212000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 0 \r\n test  2024-01-26T11:36:28.227000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 1 \r\n test  2024-01-26T11:36:28.274000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 2 \r\n test  2024-01-26T11:36:28.290000Z TestFramework (DEBUG): Copy cache directory D:\\a\\bitcoin\\bitcoin\\test\\cache\\node0 to node 3 \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T11:36:28.337000Z TestFramework.node3 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2024-01-26T12:18:05.036000Z TestFramework.node0 (DEBUG): Stopping node \r\n test  2024-01-26T12:18:05.036000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 556, in start_nodes\r\n                                       node.wait_for_rpc_connection()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 308, in wait_for_rpc_connection\r\n                                       self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 182, in _raise_assertion_error\r\n                                       raise AssertionError(self._node_msg(msg))\r\n                                   AssertionError: [node 0] Unable to connect to bitcoind after 2400s\r\n                                   During handling of the above exception, another exception occurred:\r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 130, in main\r\n                                       self.setup()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 297, in setup\r\n                                       self.setup_network()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 391, in setup_network\r\n                                       self.setup_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 413, in setup_nodes\r\n                                       self.start_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 559, in start_nodes\r\n                                       self.stop_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 574, in stop_nodes\r\n                                       node.stop_node(wait=wait, wait_until_stopped=False)\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 369, in stop_node\r\n                                       self.stop(wait=wait)\r\n                                       ^^^^^^^^^\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 199, in __getattr__\r\n                                       assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\n                                   AssertionError: [node 0] Error: no RPC connection\r\n test  2024-01-26T12:18:05.036000Z TestFramework (DEBUG): Closing down network thread \r\n test  2024-01-26T12:18:05.090000Z TestFramework (INFO): Stopping nodes \r\n test  2024-01-26T12:18:05.090000Z TestFramework.node0 (DEBUG): Stopping node \r\n````",
   "closed_at" : "2024-01-26T13:25:21Z",
   "closed_by" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   },
   "comments" : 2,
   "comments_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29326/comments",
   "created_at" : "2024-01-26T13:09:07Z",
   "events_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29326/events",
   "html_url" : "https://github.com/bitcoin/bitcoin/issues/29326",
   "id" : 2102190435,
   "labels" : [],
   "labels_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29326/labels{/name}",
   "locked" : false,
   "milestone" : null,
   "node_id" : "I_kwDOABII5859TOFj",
   "number" : 29326,
   "performed_via_github_app" : null,
   "reactions" : {
      "+1" : 0,
      "-1" : 0,
      "confused" : 0,
      "eyes" : 0,
      "heart" : 0,
      "hooray" : 0,
      "laugh" : 0,
      "rocket" : 0,
      "total_count" : 0,
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29326/reactions"
   },
   "repository_url" : "https://api.github.com/repos/bitcoin/bitcoin",
   "state" : "closed",
   "state_reason" : "completed",
   "timeline_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29326/timeline",
   "title" : "ci: failure in feature_index_prune.py (MSVC)",
   "updated_at" : "2024-01-26T13:25:21Z",
   "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/29326",
   "user" : {
      "avatar_url" : "https://avatars.githubusercontent.com/u/863730?v=4",
      "events_url" : "https://api.github.com/users/fanquake/events{/privacy}",
      "followers_url" : "https://api.github.com/users/fanquake/followers",
      "following_url" : "https://api.github.com/users/fanquake/following{/other_user}",
      "gists_url" : "https://api.github.com/users/fanquake/gists{/gist_id}",
      "gravatar_id" : "",
      "html_url" : "https://github.com/fanquake",
      "id" : 863730,
      "login" : "fanquake",
      "node_id" : "MDQ6VXNlcjg2MzczMA==",
      "organizations_url" : "https://api.github.com/users/fanquake/orgs",
      "received_events_url" : "https://api.github.com/users/fanquake/received_events",
      "repos_url" : "https://api.github.com/users/fanquake/repos",
      "site_admin" : false,
      "starred_url" : "https://api.github.com/users/fanquake/starred{/owner}{/repo}",
      "subscriptions_url" : "https://api.github.com/users/fanquake/subscriptions",
      "type" : "User",
      "url" : "https://api.github.com/users/fanquake"
   }
}
