[
   {
      "author_association" : "MEMBER",
      "body" : "So it appears that this was triggered by LevelDB failing to write to disk.\r\n\r\nSome questions:\r\n* Why didn't our own disk space check detect this long before it happened? @jb55 was anything else quickly filling your disk at the same time, which could cause our own check to not being frequent enough?\r\n* Did Bitcoin Core shut down after this happened?\r\n\r\nBased on your comments on IRC, it seems that normal restarting didn't fix the problem. So that suggests that while there was some LevelDB error... Bitcoin Core still managed to (incorrectly) write to disk that the block was invalid. It shouldn't conclude that in the first place, but it's somewhat strange that even after a system error it still managed to actually commit that to disk.",
      "created_at" : "2022-09-16T17:50:50Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26112#issuecomment-1249641810",
      "id" : 1249641810,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26112",
      "node_id" : "IC_kwDOABII585KfAVS",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1249641810/reactions"
      },
      "updated_at" : "2022-09-16T17:50:50Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1249641810",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "> Why didn't our own disk space check detect this long before it happened? @jb55 was anything else quickly filling your disk at the same time, which could cause our own check to not being frequent enough?\r\n\r\nyes this is very possible, I run nixos and frequently use nix-shell, etc which downloads things and fills up my disk pretty quickly.\r\n\r\n> Did Bitcoin Core shut down after this happened?\r\n\r\nyes, here's the full log:\r\n\r\n```\r\n2022-09-05T00:28:55Z UpdateTip: new best=000000000000000000087e337539b369b19570a88c493725020266387d22dac0 height=752167 version=0x2ce8e004 log2_work=93.70770\r\n7 tx=761139817 date='2022-09-01T15:00:06Z' progress=0.998887 cache=146.8MiB(1101860txo)\r\n2022-09-05T00:28:55Z Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:55Z You can use -debug=leveldb to get more complete diagnostic messages\r\n2022-09-05T00:28:55Z *** System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:55Z Error: A fatal internal error occurred, see debug.log for details\r\n2022-09-05T00:28:56Z ERROR: ProcessNewBlock: ActivateBestChain failed (System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chains\r\ntate/2963623.ldb: No space left on device)\r\n2022-09-05T00:28:56Z ERROR: ConnectBlock: Consensus::CheckTxInputs: 221fa678c5c9953d6cd17e584f05c12ab10ba0f2fc8e8131e266f3f0e9819848, bad-txns-inputs-missing\r\norspent, CheckTxInputs: inputs missing/spent\r\n2022-09-05T00:28:56Z InvalidChainFound: invalid block=000000000000000000079ba062298aa7cef1888f870c23e303a361c19b097ff8  height=752168  log2_work=93.707719  date=2022-09-01T15:13:42Z\r\n2022-09-05T00:28:56Z InvalidChainFound:  current best=000000000000000000087e337539b369b19570a88c493725020266387d22dac0  height=752167  log2_work=93.707707  date=2022-09-01T15:00:06Z\r\n2022-09-05T00:28:56Z ERROR: ConnectTip: ConnectBlock 000000000000000000079ba062298aa7cef1888f870c23e303a361c19b097ff8 failed, bad-txns-inputs-missingorspent, CheckTxInputs: inputs missing/spent\r\n2022-09-05T00:28:56Z InvalidChainFound: invalid block=000000000000000000079ba062298aa7cef1888f870c23e303a361c19b097ff8  height=752168  log2_work=93.707719  date=2022-09-01T15:13:42Z\r\norspent, CheckTxInputs: inputs missing/spent\r\n2022-09-05T00:28:57Z ERROR: ProcessNewBlock: ActivateBestChain failed (System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device)\r\n2022-09-05T00:28:57Z msghand thread exit\r\n2022-09-05T00:28:57Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started\r\n CheckTxInputs: inputs missing/spent\r\n2022-09-05T00:28:56Z InvalidChainFound: invalid block=000000000000000000079ba062298aa7cef1888f870c23e303a361c19b097ff8  height=752168  log2_work=93.707719  date=2022-09-01T15:13:42Z\r\n2022-09-05T00:28:56Z InvalidChainFound:  current best=000000000000000000087e337539b369b19570a88c493725020266387d22dac0  height=752167  log2_work=93.707707  date=2022-09-01T15:00:06Z\r\n2022-09-05T00:28:57Z tor: Thread interrupt\r\n2022-09-05T00:28:57Z torcontrol thread exit\r\n2022-09-05T00:28:57Z opencon thread exit\r\n2022-09-05T00:28:57Z addcon thread exit\r\n2022-09-05T00:28:57Z Shutdown: In progress...\r\n2022-09-05T00:28:57Z net thread exit\r\n2022-09-05T00:28:57Z Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:57Z You can use -debug=leveldb to get more complete diagnostic messages\r\n2022-09-05T00:28:57Z *** System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:57Z Error: A fatal internal error occurred, see debug.log for details\r\n2022-09-05T00:28:57Z ERROR: ProcessNewBlock: ActivateBestChain failed (System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chains\r\ntate/2963623.ldb: No space left on device)\r\n2022-09-05T00:28:57Z msghand thread exit\r\n2022-09-05T00:28:57Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started\r\n2022-09-05T00:28:57Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat completed (0.00s)\r\n2022-09-05T00:28:57Z scheduler thread exit\r\n2022-09-05T00:28:57Z Writing 0 unbroadcast transactions to disk.\r\n2022-09-05T00:28:57Z Dumped mempool: 0.001682s to copy, 0.015307s to dump\r\n2022-09-05T00:28:57Z Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:57Z You can use -debug=leveldb to get more complete diagnostic messages\r\n2022-09-05T00:28:57Z *** System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:57Z Error: A fatal internal error occurred, see debug.log for details\r\n2022-09-05T00:28:57Z ForceFlushStateToDisk: failed to flush state (System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device)\r\n2022-09-05T00:28:57Z Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:57Z You can use -debug=leveldb to get more complete diagnostic messages\r\n2022-09-05T00:28:57Z *** System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device\r\n2022-09-05T00:28:57Z Error: A fatal internal error occurred, see debug.log for details\r\n2022-09-05T00:28:57Z ForceFlushStateToDisk: failed to flush state (System error while flushing: Fatal LevelDB error: IO error: /home/jb55/.bitcoin/chainstate/2963623.ldb: No space left on device)\r\n2022-09-05T00:28:57Z [personal] Releasing wallet\r\n2022-09-05T00:28:57Z [old-wallet] Releasing wallet\r\n2022-09-05T00:28:58Z Shutdown: done\r\n```\r\n",
      "created_at" : "2022-09-16T17:56:11Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26112#issuecomment-1249647168",
      "id" : 1249647168,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26112",
      "node_id" : "IC_kwDOABII585KfBpA",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1249647168/reactions"
      },
      "updated_at" : "2022-09-16T17:56:11Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1249647168",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/45598?v=4",
         "events_url" : "https://api.github.com/users/jb55/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jb55/followers",
         "following_url" : "https://api.github.com/users/jb55/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jb55/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jb55",
         "id" : 45598,
         "login" : "jb55",
         "node_id" : "MDQ6VXNlcjQ1NTk4",
         "organizations_url" : "https://api.github.com/users/jb55/orgs",
         "received_events_url" : "https://api.github.com/users/jb55/received_events",
         "repos_url" : "https://api.github.com/users/jb55/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jb55/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jb55/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jb55"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "A guess about what might be happening:\r\n\r\n`CCoinsViewErrorCatcher`, the wrapper class used around `CCoinsViewDB` that's supposed to detect these problems and forcefully exit the application, has an override for `GetCoins`. But in `CheckTxInputs`, `HaveInputs` is first invoked, which on its turn calls `HaveCoin`. `HaveCoin` is implemented in `CCoinsViewDB`, but not in `CCoinsViewErrorCatcher`, and thus the disk read exception escapes.\r\n\r\nA solution may be to just add an override for `HaveCoin` in `CCoinsViewErrorCatcher`.",
      "created_at" : "2022-09-16T18:34:20Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26112#issuecomment-1249683401",
      "id" : 1249683401,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26112",
      "node_id" : "IC_kwDOABII585KfKfJ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1249683401/reactions"
      },
      "updated_at" : "2022-09-16T18:34:20Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1249683401",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/548488?v=4",
         "events_url" : "https://api.github.com/users/sipa/events{/privacy}",
         "followers_url" : "https://api.github.com/users/sipa/followers",
         "following_url" : "https://api.github.com/users/sipa/following{/other_user}",
         "gists_url" : "https://api.github.com/users/sipa/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/sipa",
         "id" : 548488,
         "login" : "sipa",
         "node_id" : "MDQ6VXNlcjU0ODQ4OA==",
         "organizations_url" : "https://api.github.com/users/sipa/orgs",
         "received_events_url" : "https://api.github.com/users/sipa/received_events",
         "repos_url" : "https://api.github.com/users/sipa/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/sipa/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/sipa/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/sipa"
      }
   },
   {
      "author_association" : "MEMBER",
      "body" : "Removed from the milestone, as this is not a regression, nor a fix is available right now.",
      "created_at" : "2022-10-17T17:09:09Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26112#issuecomment-1281185512",
      "id" : 1281185512,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26112",
      "node_id" : "IC_kwDOABII585MXVbo",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1281185512/reactions"
      },
      "updated_at" : "2022-10-17T17:09:09Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1281185512",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/6399679?v=4",
         "events_url" : "https://api.github.com/users/MarcoFalke/events{/privacy}",
         "followers_url" : "https://api.github.com/users/MarcoFalke/followers",
         "following_url" : "https://api.github.com/users/MarcoFalke/following{/other_user}",
         "gists_url" : "https://api.github.com/users/MarcoFalke/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/MarcoFalke",
         "id" : 6399679,
         "login" : "MarcoFalke",
         "node_id" : "MDQ6VXNlcjYzOTk2Nzk=",
         "organizations_url" : "https://api.github.com/users/MarcoFalke/orgs",
         "received_events_url" : "https://api.github.com/users/MarcoFalke/received_events",
         "repos_url" : "https://api.github.com/users/MarcoFalke/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/MarcoFalke/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/MarcoFalke/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/MarcoFalke"
      }
   },
   {
      "author_association" : "CONTRIBUTOR",
      "body" : "awesome, thanks @aureleoules !",
      "created_at" : "2023-10-11T04:32:13Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26112#issuecomment-1756768649",
      "id" : 1756768649,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26112",
      "node_id" : "IC_kwDOABII585otimJ",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1756768649/reactions"
      },
      "updated_at" : "2023-10-11T04:32:13Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1756768649",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/45598?v=4",
         "events_url" : "https://api.github.com/users/jb55/events{/privacy}",
         "followers_url" : "https://api.github.com/users/jb55/followers",
         "following_url" : "https://api.github.com/users/jb55/following{/other_user}",
         "gists_url" : "https://api.github.com/users/jb55/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/jb55",
         "id" : 45598,
         "login" : "jb55",
         "node_id" : "MDQ6VXNlcjQ1NTk4",
         "organizations_url" : "https://api.github.com/users/jb55/orgs",
         "received_events_url" : "https://api.github.com/users/jb55/received_events",
         "repos_url" : "https://api.github.com/users/jb55/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/jb55/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/jb55/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/jb55"
      }
   },
   {
      "author_association" : "NONE",
      "body" : "61a6c3b0e9a8dab5c5f845af4becde817539133c",
      "created_at" : "2023-11-12T11:18:35Z",
      "html_url" : "https://github.com/bitcoin/bitcoin/issues/26112#issuecomment-1807096155",
      "id" : 1807096155,
      "issue_url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/26112",
      "node_id" : "IC_kwDOABII585rthlb",
      "performed_via_github_app" : null,
      "reactions" : {
         "+1" : 0,
         "-1" : 0,
         "confused" : 0,
         "eyes" : 0,
         "heart" : 0,
         "hooray" : 0,
         "laugh" : 0,
         "rocket" : 0,
         "total_count" : 0,
         "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1807096155/reactions"
      },
      "updated_at" : "2023-11-12T11:18:35Z",
      "url" : "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1807096155",
      "user" : {
         "avatar_url" : "https://avatars.githubusercontent.com/u/143917225?v=4",
         "events_url" : "https://api.github.com/users/Mikey4010/events{/privacy}",
         "followers_url" : "https://api.github.com/users/Mikey4010/followers",
         "following_url" : "https://api.github.com/users/Mikey4010/following{/other_user}",
         "gists_url" : "https://api.github.com/users/Mikey4010/gists{/gist_id}",
         "gravatar_id" : "",
         "html_url" : "https://github.com/Mikey4010",
         "id" : 143917225,
         "login" : "Mikey4010",
         "node_id" : "U_kgDOCJQAqQ",
         "organizations_url" : "https://api.github.com/users/Mikey4010/orgs",
         "received_events_url" : "https://api.github.com/users/Mikey4010/received_events",
         "repos_url" : "https://api.github.com/users/Mikey4010/repos",
         "site_admin" : false,
         "starred_url" : "https://api.github.com/users/Mikey4010/starred{/owner}{/repo}",
         "subscriptions_url" : "https://api.github.com/users/Mikey4010/subscriptions",
         "type" : "User",
         "url" : "https://api.github.com/users/Mikey4010"
      }
   }
]
